### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by robshizzle** [coderholic/pyradio#115]
After a recent python update in Arch Linux, I now get...

Traceback (most recent call last):
  File "/home/me/.local/bin/pyradio", line 8, in <module>
    sys.exit(shell())
  File "/home/me/.local/lib/python3.9/site-packages/pyradio/main.py", line 54, in shell
    curses.wrapper(pyradio.setup)
  File "/usr/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/me/.local/lib/python3.9/site-packages/pyradio/radio.py", line 56, in setup
    self.player = player.probePlayer()(self.log)
TypeError: 'NoneType' object is not callable

Is there anything I can do about this, or is this a pyradio and/or python problem? Thanks for any help.

**Comment by s-n-g** [comment]
This is line 56 of file *radio.py*
https://github.com/coderholic/pyradio/blob/5a3535132e904822ecaf7184b2f46b6d1f630e6f/pyradio/radio.py#L56

Are you sure you are running **this** pyradio and not a fork/snap/whatever?

**Comment by s-n-g** [comment]
Anyway, since you have updated python to 3.9 - i suppose this is the case), you have to manually reinstall all python packages you had previously installed from source.
