### ISSUE TITLE
Fails to launch with module import error (fresh install)

### ISSUE THREAD

**Issue by RaeedAhmed** [coderholic/pyradio#129]
Debian sid 5.10.26-1, Python 3.9.2 installed

Traceback (most recent call last):
  File "/usr/local/bin/pyradio", line 33, in <module>
    sys.exit(load_entry_point('pyradio==0.8.9.1', 'console_scripts', 'pyradio')())
  File "/usr/local/bin/pyradio", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/pyradio-0.8.9.1-py3.9.egg/pyradio/main.py", line 11, in <module>
    from .radio import PyRadio
  File "/usr/local/lib/python3.9/dist-packages/pyradio-0.8.9.1-py3.9.egg/pyradio/radio.py", line 32, in <module>
    from .config import HAS_REQUESTS
  File "/usr/local/lib/python3.9/dist-packages/pyradio-0.8.9.1-py3.9.egg/pyradio/config.py", line 17, in <module>
    from .browser import PyRadioStationsBrowser, probeBrowsers
  File "/usr/local/lib/python3.9/dist-packages/pyradio-0.8.9.1-py3.9.egg/pyradio/browser.py", line 3, in <module>
    from dns import resolver
ModuleNotFoundError: No module named 'dns'

**Comment by s-n-g** [comment]
Hi @RaeedAhmed 

I'm sorry if this is not clear on the documentation...

On debian you need to install [python3-dnspython](https://packages.debian.org/stretch/python3-dnspython) for python3

So

```sudo apt install python3-dnspython```

will solve the problem.
