### ISSUE TITLE
Playback disconnects/crashes after few seconds (Windows)

### ISSUE THREAD

**Issue by RaeedAhmed** [coderholic/pyradio#148]
After selecting a station to play, the music stream correctly plays and the status bar correctly displays the song name/artist. However, the status bar quickly changes to "Connecting to: [station]" while the stream is still functioning. Playback stops when pyradio 'fails to connect'.

Windows 10 21H2
player: MPV (following instructions in this repo)

This is the traceback when quitting pyradio:

```
Exception in thread Thread-4 (updateMPVStatus):
Traceback (most recent call last):
  File "C:\Users\Raeed\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Raeed\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Raeed\AppData\Local\Programs\Python\Python310\lib\site-packages\pyradio-0.8.9.12-py3.10.egg\pyradio\player.py", line 790, in updateMPVStatus
    if self._get_mpv_metadata(n, stop):
  File "C:\Users\Raeed\AppData\Local\Programs\Python\Python310\lib\site-packages\pyradio-0.8.9.12-py3.10.egg\pyradio\player.py", line 1117, in _get_mpv_metadata
    return self._set_mpv_playback_is_on(stop, enable_crash_detection_function)
NameError: name 'enable_crash_detection_function' is not defined
```

EDIT:
Some stations seem to be working normally. Here are a couple of streams that have the issue:
"Dogglounge" - https://www.dogglounge.com:8000
"DJ Dacha mixes" - https://deeperlink.com:8002/stream

And here is an example stream that works normally:
"Dinamo.fm Deep" - https://channels.dinamo.fm/deep-mp3

As mentioned below all stations work normally on linux

**Comment by RaeedAhmed** [comment]
I should note that this problem does not occur on my void linux installation

**Comment by s-n-g** [comment]
Hi @RaeedAhmed 

I cannot reproduce in Window 7, 10 or 11, but I may have a clue on what is breaking...

Can you please download this:

https://u.pcloud.link/publink/show?code=XZLyJ7VZFlftH6IRsSpzDmrnoJbpChuLCCoV

Then extract the `pyradio` folder in your home directory, open a console, and execute:

```
cd pyradio
devel\build_install_pyradio
```

I hope this works...

**Comment by RaeedAhmed** [comment]
Hey @s-n-g ,
The patch worked! I tried all the stations that were giving me problems, and the issues are fixed! As a side note, the streams across the board load a lot faster. Thank you so much for the work you put into this project, I use it every day :)

**Comment by RaeedAhmed** [comment]
@s-n-g The .13 release code has a bug compared to the temporary patch you sent me. I noticed that with the release that for some stations, the title would flicker for a split second but then default to "Playing [station]" (but the stream doesn't crash). On the temporary patch, title is displayed as expected. 

The traceback when the error occurs is:

```
Exception in thread Thread-4 (updateMPVStatus):
Traceback (most recent call last):
  File "C:\Users\Raeed\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Raeed\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Raeed\AppData\Local\Programs\Python\Python310\lib\site-packages\pyradio-0.8.9.13-py3.10.egg\pyradio\player.py", line 817, in updateMPVStatus
    if self._get_mpv_metadata(n, stop, enable_crash_detection_function):
  File "C:\Users\Raeed\AppData\Local\Programs\Python\Python310\lib\site-packages\pyradio-0.8.9.13-py3.10.egg\pyradio\player.py", line 1144, in _get_mpv_metadata
    return self._set_mpv_playback_is_on(stop, enable_crash_detection_function)
  File "C:\Users\Raeed\AppData\Local\Programs\Python\Python310\lib\site-packages\pyradio-0.8.9.13-py3.10.egg\pyradio\player.py", line 1243, in _set_mpv_playback_is_on
    enable_crash_detection_function()
TypeError: 'list' object is not callable
```

**Comment by s-n-g** [comment]
Hi @RaeedAhmed 

Probably something not copied correctly from Windows to linux...

Sorry about that...

I will have a look as soon as possible (I'm at work right now)...

**Comment by s-n-g** [comment]
ok, **0.8.9.14** fixed this stupid bug :blush:
