### ISSUE TITLE
MacOS 'python install.py' -- Error: Cannot contact GitHub

### ISSUE THREAD

**Issue by filipzeman** [coderholic/pyradio#151]
Hi,

when installing from the source the newest version of pyradio, I get the following error when performing 'python install.py':
`Error: Cannot contact GitHub!
       Please make sure your internet connection is up and try again.`

I am connected to the internet, wget downloaded install.py a few seconds ago.

**macOS Monterey 12.2, Python 3.9.6**

Do you have any idea? What information should I provide you with?

**Comment by s-n-g** [comment]
Ηι @filipzeman 
I believe this will fix it...

```
python3 -m pip install requests
```

the try again

```
python3 install.py
```

**Comment by s-n-g** [comment]
Oh, and btw, you will probably have to install ```requests```:

```
python3 -m pip install requests
python3 install.py
```

**Comment by filipzeman** [comment]
Thanks, I tried using python3 too, but without success.

I tried to install requests library, but already have it installed.

Do you have any other idea? Thanks a lot for any help

**Comment by s-n-g** [comment]
Let's just try to execute the same code without error checking...

Just save this code in a file, for example `test-tags.py`

```
from urllib.request import urlopen
url = 'https://api.github.com/repos/coderholic/pyradio/tags'
with urlopen(url) as https_response:
    ret = https_response.read()
print(ret)
```

Execute it in a terminal:

```
python3 test-tags.py
```

and finally post anything it prints...

**Comment by filipzeman** [comment]
**Output**:
` python3 test-tags.py                                                                                                                                                                                 ✔  at 12:47:42
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1426, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fzeman/Applications/PyRadio/test-tags.py", line 3, in <module>
    with urlopen(url) as https_response:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>`

**Comment by s-n-g** [comment]
ok, we got it...

Have a look at
https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

> Many operations in python require accessing things via https. This includes pip install, or just using http.client.HTTPSConnection, or any modules or applications that use these things internally.

> If python was installed from the official python pkg installer, downloaded from https://python.org/, then it uses an internal version of openssl, and contains no root certificates.

The commands to execute are here:
https://stackoverflow.com/questions/68275857/urllib-error-urlerror-urlopen-error-ssl-certificate-verify-failed-certifica/70495761#70495761

I hope that fixes everything...

**Comment by s-n-g** [comment]
ok, closing this one, since

1. it's not a `pyradio` issue
2. got no responce for almost two weeks
