### ISSUE TITLE
Pyradio crashes when trying to select a different station from the list

### ISSUE THREAD

**Issue by PhilT001** [coderholic/pyradio#157]
Just upgraded to 0.8.9.19. If I try to select a different station by using my keyboard down arrow key, Pyradio crashes.

(Nokia-N810-43-7) pyradio $ pyradio
Reading config...
Reading playlist...
No handlers could be found for logger "pyradio.config"
Traceback (most recent call last):
  File "/usr/bin/pyradio", line 11, in <module>
    load_entry_point('pyradio==0.8.9.19', 'console_scripts', 'pyradio')()
  File "/usr/lib/python2.7/site-packages/pyradio/main.py", line 443, in shell
    curses.wrapper(pyradio.setup)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python2.7/site-packages/pyradio/radio.py", line 593, in setup
    self.run()
  File "/usr/lib/python2.7/site-packages/pyradio/radio.py", line 1116, in run
    ret = self.keypress(c)
  File "/usr/lib/python2.7/site-packages/pyradio/radio.py", line 6332, in keypress
    elif chr(char) in self._global_functions.keys():
ValueError: chr() arg not in range(256)

**Comment by s-n-g** [comment]
oh, I see you are on 2.7... and I did not check this one on 2.7...

Working on it...

**Comment by s-n-g** [comment]
fixed in **0.8.9.20**
