### ISSUE TITLE
Not possible to insert a  capital-"T" in Radio Browser search fields

### ISSUE THREAD

**Issue by Knusper** [coderholic/pyradio#164]
Pressing 'T' inside the input file to specify a search string containing this letter does not work.  It just toggles transparency.  If I understand the documentation correct, this should not happen, and '\T' should toggle the transparency here...

**Comment by s-n-g** [comment]
Hi @Knusper 

I am afraid I cannot reproduce this... ate least on linux

Can you please provide more info?
(OS/distro, pyradio version, source of installation)

**Comment by s-n-g** [comment]
Oh, ok I found it...
You mean the radiobrowser help...
Ok, let me have a look...

**Comment by Knusper** [comment]
![image](https://user-images.githubusercontent.com/4704406/184511003-6fb9d2cb-aa65-4347-b5ee-607053609ea1.png)
 there

**Comment by s-n-g** [comment]
It should be fixed in **0.8.9.25**
Please do check it out and report any other problems...

Thank you for reporting this one!

**Comment by Knusper** [comment]
Just run the update and it is fixed, all text files in the search box accept now capital T's;  thanks so much for hacking! 

I got an error message when running the update regarding logging (I remember seeing this update previously as well when doing the update).  I past below, but I close this bug here, since this is unrelated.

```

--- Logging error ---
Traceback (most recent call last):
  File "/home/ehere/.local/lib/python3.7/site-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/home/ehere/.local/lib/python3.7/site-packages/pip/_vendor/rich/console.py", line 1673, in print
    extend(render(renderable, render_options))
  File "/home/ehere/.local/lib/python3.7/site-packages/pip/_vendor/rich/console.py", line 1305, in render
    for render_output in iter_render:
  File "/home/ehere/.local/lib/python3.7/site-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
    for line in lines:
  File "/home/ehere/.local/lib/python3.7/site-packages/pip/_vendor/rich/segment.py", line 249, in split_lines
    for segment in segments:
  File "/home/ehere/.local/lib/python3.7/site-packages/pip/_vendor/rich/console.py", line 1283, in render
    renderable = rich_cast(renderable)
  File "/home/ehere/.local/lib/python3.7/site-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
    renderable = cast_method()
  File "/home/ehere/.local/lib/python3.7/site-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
    pip_cmd = get_best_invocation_for_this_pip()
  File "/home/ehere/.local/lib/python3.7/site-packages/pip/_internal/utils/entrypoints.py", line 60, in get_best_invocation_for_this_pip
    os.path.join(binary_prefix, exe_name),
  File "/usr/lib/python3.7/genericpath.py", line 97, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/usr/bin/pip'
Call stack:
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ehere/.local/lib/python3.7/site-packages/pip/__main__.py", line 31, in <module>
    sys.exit(_main())
  File "/home/ehere/.local/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/home/ehere/.local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/home/ehere/.local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    self.handle_pip_version_check(options)
  File "/home/ehere/.local/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 190, in handle_pip_version_check
    pip_self_version_check(session, options)
  File "/home/ehere/.local/lib/python3.7/site-packages/pip/_internal/self_outdated_check.py", line 236, in pip_self_version_check
    logger.info("[present-rich] %s", upgrade_prompt)
  File "/usr/lib/python3.7/logging/__init__.py", line 1383, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/home/ehere/.local/lib/python3.7/site-packages/pip/_internal/utils/logging.py", line 179, in emit
    self.handleError(record)
Message: '[present-rich] %s'
Arguments: (UpgradePrompt(old='22.2', new='22.2.2'),)

```

**Comment by s-n-g** [comment]
This error you got here, is not relevant to `pyradio`, I think...

I think this has something to do with your `pip` installation... I see `pip` is installed locally (as user `ehere`) which I believe is not a good practice. You should uninstall your local `pip` installation (install system wide `pip` beforehand).
