### ISSUE TITLE
Installation error on a Pi Zero W

### ISSUE THREAD

**Issue by undeterred965** [coderholic/pyradio#203]
Received the below error upon installing and asked me to report...
Background information:

1. Clean installation of Raspberry Pi OS Lite (bullseye) with `/boot/config.txt` containing the line `dtoverlay=hifiberry-dac` and the following commented out `#dtparam=audio=on`
2. Followed the installation guide `https://github.com/coderholic/pyradio/blob/master/linux-pipx.md#system-dependent-installation---debian`

```
pi@radio:~ $ cd
pi@radio:~ $ python3 install.py

                     _____       _____           _ _
                    |  __ \     |  __ \         | (_)
                    | |__) |   _| |__) |__ _  __| |_  ___
                    |  ___/ | | |  _  // _` |/ _` | |/ _ \
                    | |   | |_| | | \ \ (_| | (_| | | (_) |
                    |_|    \__, |_|  \_\__,_|\__,_|_|\___/
                            __/ |
                           |___/

                               installation script
                                   running on

                   _____       _   _                    ____
                  |  __ \     | | | |                  |___ \
                  | |__) |   _| |_| |__   ___  _ __      __) |
                  |  ___/ | | | __| '_ \ / _ \| '_ \    |__ <
                  | |   | |_| | |_| | | | (_) | | | |   ___) |
                  |_|    \__, |\__|_| |_|\___/|_| |_|  |____/
                          __/ |
                         |___/



Installing PyRadio...
Using directory: "/home/pi/.config/pyradio/data/.cache"
Downloading PyRadio source code...
  url: "https://github.com/coderholic/pyradio/archive/0.9.2.13.zip"
  filename: "/home/pi/.config/pyradio/data/.cache/pyradio-0.9.2.13.zip"
Extracting RyRadio source code...
Traceback (most recent call last):
  File "/usr/bin/pipx", line 11, in <module>
    load_entry_point('pipx==0.12.3.1', 'console_scripts', 'pipx')()
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 496, in cli
    exit(run_pipx_command(parsed_pipx_args, binary_args))
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 147, in run_pipx_command
    commands.install(
  File "/usr/lib/python3/dist-packages/pipx/commands.py", line 312, in install
    if venv.get_venv_metadata_for_package(package).package_version is None:
  File "/usr/lib/python3/dist-packages/pipx/Venv.py", line 65, in get_venv_metadata_for_package
    data = json.loads(
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
The installation has failed!!!
Please report this at https://github.com/coderholic/pyradio/issues



An error occured during the installation!
This should have never had happened...
Please report this at http://github.com/coderholic/pyradio/issues
```

**Comment by s-n-g** [comment]
Hi @undeterred965 

It seems this is a known python3.9/pipx bug?

https://github.com/pypa/pipx/issues/702

Can you please try this?

```
cd /home/pi/.config/pyradio/data/.cache/
unzip pyradio-0.9.2.13.zip
cd pyradio-0.9.2.13/devel
sed -i 's/pipx install /python3 -m pipx install /' build_install_pyradio
cd ..
./devel/build_install_pyradio
```

**Comment by undeterred965** [comment]
Thanks for getting back to me so quickly.
Install seemed to go fine. I received the following message
```
Successfully installed pyradio-0.9.2.13
```

**Comment by s-n-g** [comment]
This is great!
Can you actually execute pyradio?

**Comment by s-n-g** [comment]
Ok, great!
I'm updating the installation script!

Closing this one
Thank you fore reporting!
