### ISSUE TITLE
Macos 14 installation can't find pipx

### ISSUE THREAD

**Issue by Bellavene** [coderholic/pyradio#205]
As described in the title, install.py can't find pipx.

**Comment by s-n-g** [comment]
Hi @Bellavene 

I am trying to install macos 14 on vm but the installer gets to an error...

I just made a clean install on macos 12 (monterey) and everything work as expected; `pipx` was found and `pyradio` was installed successfully...

Is this a **Sonoma** thing?

Have all the steps all the way to `python3 install.py` from [PyRadio macOS installation](https://github.com/coderholic/pyradio/blob/master/macos.md) worked fine for you?

In the meantime, I'm giving it another go with the Sonoma installation...

**Comment by s-n-g** [comment]
BTW, what does this command report?
```
python3 -m pipx --version
```

**Comment by FedeFofo** [comment]
I am having the same issue running MacOS Sonoma.

> BTW, what does this command report?
> python3 -m pipx --version

It returns 1.2.1

**Comment by s-n-g** [comment]
Can you please post the output of `python install.py` ?

BTW, have you recently upgraded macos from a previous version?
I mean did `python` get update recently?

**Comment by FedeFofo** [comment]
> Can you please post the output?

This is the output:
```
Installing PyRadio...
Using directory: "/Users/jamesesser/.config/pyradio/data/.cache"
Downloading PyRadio source code...
  url: "https://github.com/coderholic/pyradio/archive/0.9.2.19.zip"
  filename: "/Users/jamesesser/.config/pyradio/data/.cache/pyradio-0.9.2.19.zip"
Extracting RyRadio source code...


Error: pipx not found.
       Please install pipx and try again


An error occured during the installation!
This should have never had happened...
Please report this at http://github.com/coderholic/pyradio/issues

```

I am running Python 3.11.4

Should I try to update to 3.12?

**Comment by FedeFofo** [comment]
I just updated to Python 3.12. Nothing changed as far as the error.

**Comment by s-n-g** [comment]
I think that the problem is that the default python is `python2` instead of `python3`...

What does this gives back?

```
python --version
```

**Comment by FedeFofo** [comment]
python --version
`zsh: command not found: python`
python3 --version
`Python 3.12.0`
pipx list
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/pipx", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pipx/main.py", line 858, in cli
    setup(parsed_pipx_args)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pipx/main.py", line 805, in setup
    mkdir(constants.LOCAL_BIN_DIR)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pipx/util.py", line 82, in mkdir
    path.mkdir(parents=True, exist_ok=True)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/pathlib.py", line 1312, in mkdir
    os.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/Applications/VLC.app/Contents/MacOS/VLC'

```
python3 -m pipx list
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pipx/__main__.py", line 14, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pipx/main.py", line 858, in cli
    setup(parsed_pipx_args)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pipx/main.py", line 805, in setup
    mkdir(constants.LOCAL_BIN_DIR)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pipx/util.py", line 82, in mkdir
    path.mkdir(parents=True, exist_ok=True)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/pathlib.py", line 1312, in mkdir
    os.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/Applications/VLC.app/Contents/MacOS/VLC'
```
which python3
`/Library/Frameworks/Python.framework/Versions/3.12/bin/python3`
echo "$PATH"
`/Library/Frameworks/Python.framework/Versions/3.12/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin`

**Comment by s-n-g** [comment]
Here's what I see from this

1. `python` does not exist at all
2. `pipx list` gives an error (I suppose this is because you have updated python to 3.12 but pipx uses 3.11 shared libraries?)
3. `pipx ensurepath` has not been executed yet?

This is a script that will
- download **PyRadio 0.9.2.19**
- download and copy a couple of files into it
- execute the setup (which will hopefully be successful)
- execute `pipx ensurepath`

Just copy and paste into a file, save it as `issue205` in your home folder, and execute it

```
cd
chmod +x issue205
./issue205
```


**issue205**
```
#!/bin/bash
rm -rf ~/.local/pipx
cd
rm -rf tmp_pyradio 2>/dev/null
rm install.py build_install_pyradio 2>/dev/null
mkdir tmp_pyradio
cd tmp_pyradio
curl -L  https://github.com/coderholic/pyradio/archive/refs/tags/0.9.2.19.tar.gz -o 0.9.2.19.tar.gz
tar xzf 0.9.2.19.tar.gz
curl -L https://github.com/s-n-g/pyradio/raw/devel/devel/build_install_pyradio -o build_install_pyradio
mv build_install_pyradio pyradio-0.9.2.19/devel
chmod +x pyradio-0.9.2.19/devel/build_install_pyradio
curl -L https://github.com/s-n-g/pyradio/raw/devel/pyradio/install.py -o install.py
mv install.py pyradio-0.9.2.19/pyradio
cd pyradio-0.9.2.19
./devel/build_install_pyradio
python3 -m pipx ensurepath
```

Hope it works... I am sorry I cannot test it myself on **Sonoma**, I still cannot complete the installation... I have tested it on **Monteray**...

**Comment by FedeFofo** [comment]
It didn't work, this is the output it gave:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1392k    0 1392k    0     0  1109k      0 --:--:--  0:00:01 --:--:-- 2186k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 15390  100 15390    0     0  16577      0 --:--:-- --:--:-- --:--:-- 16577
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 61590  100 61590    0     0  64365      0 --:--:-- --:--:-- --:--:-- 64365


Error: pipx not found.
       Please install pipx and try again
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pipx/__main__.py", line 14, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pipx/main.py", line 858, in cli
    setup(parsed_pipx_args)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pipx/main.py", line 805, in setup
    mkdir(constants.LOCAL_BIN_DIR)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pipx/util.py", line 82, in mkdir
    path.mkdir(parents=True, exist_ok=True)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/pathlib.py", line 1312, in mkdir
    os.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/Applications/VLC.app/Contents/MacOS/VLC'

```

**Comment by s-n-g** [comment]
This is exactly the error we got before...

And we have deleted your old pipx virtual environments (**~/.local/pipx**), which leeds me to believe that at this point it's not a pyradio problem; i think there's something wrong with your **pipx** installation...

Can you try this:

cd
cd tmp_pyradio/pyradio-0.9.2.19
python3 -m pix insatall .


If this fails, remove pipx and reinstall it, and try again

**Comment by FedeFofo** [comment]
I uninstalled pipx then reinstalled it, ran your commands, and this is what happened:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pipx/__main__.py", line 14, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pipx/main.py", line 858, in cli
    setup(parsed_pipx_args)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pipx/main.py", line 805, in setup
    mkdir(constants.LOCAL_BIN_DIR)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pipx/util.py", line 82, in mkdir
    path.mkdir(parents=True, exist_ok=True)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/pathlib.py", line 1312, in mkdir
    os.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/Applications/VLC.app/Contents/MacOS/VLC'

```

**Comment by s-n-g** [comment]
I really do not know what is going on...

It seems `pipx` is trying to create `/Applications/VLC.app/Contents/MacOS/VLC` (a directory) but it fails, because it already exists... What does `pipx` has to do with **VLC**?

Is the directory `/Applications/VLC.app/Contents/MacOS/VLC` empty by any chance?

Can it be safely deleted?

**Comment by FedeFofo** [comment]
That directory is the executable that launches VLC

**Comment by s-n-g** [comment]
BTW, I have just tried one more time to install **Sonoma**, but it still fails on me... :cry:

**Comment by s-n-g** [comment]
> That directory is the executable that launches VLC

I am lost!
What does `pipx` has to do with it?

**Comment by FedeFofo** [comment]
I have no clue! Is there any other way I can use pyradio?

**Comment by s-n-g** [comment]
Let me think...

**Comment by s-n-g** [comment]
I believe this would do it...

```
cd
cd tmp_pyradio/pyradio-0.9.2.19
rm -rf ~/.local/pipx
python3 -m pip install wheel setuptools rich requests dnspython psutil netifaces dateutil
python3 -m pip install .
```

**Comment by FedeFofo** [comment]
How do I add ~/.local/bin to my PATH?

**Comment by s-n-g** [comment]
I have corrected the command above...

To add `~/.local/bin` to your **PATH**, you will have to edit a file...

But let us just see if the installation is successful

**Comment by FedeFofo** [comment]
It built and it ran!
But, I got the error:

```
PyRadio is not able to use the player you specified.                                                                                                                                                                                                                                                                                                                                                                             This means that either this particular player is not supported                                                                                                                                                     
by PyRadio, or that you have simply misspelled its name.                                                                                                                                                           
PyRadio currently supports three players: mpv, mplayer and vlc,                                                                                                                                                    
automatically detected in this order.                                                                                                                                                                                                            
```

even though I have vlc installed.

**Comment by Bellavene** [comment]
Try mpv with custom scripts, nothing better is out there, imho

**Comment by FedeFofo** [comment]
it is too complicated to install that, I don't even have homebrew. Is it possible to still work with vlc?

**Comment by s-n-g** [comment]
There is a link you have to put in your **PATH** for that to work...

Execute `/Applications/VLC.app/Contents/MacOS/VLC` in the terminal

Does VLC starts?

**Comment by Bellavene** [comment]
Its the same as for vlc to work, it tries to find `/opt/homebrew/bin/vlc` executable. So you need anyway to `brew install vlc`

**Comment by s-n-g** [comment]
@Bellavene 

Can you execute

```
python3 -m pipx list
```

and report back its response?

**Comment by FedeFofo** [comment]
> Execute /Applications/VLC.app/Contents/MacOS/VLC in the terminal
> 
> Does VLC starts?

Yes, it does.

**Comment by s-n-g** [comment]
> Yes, it does.

Ok, wait...

**Comment by Bellavene** [comment]
python3 -m pipx list
```
venvs are in /Users/Klutchevski/.local/pipx/venvs
apps are exposed on your $PATH at /Users/Klutchevski/.local/bin
⚠️  package macnotesapp has invalid interpreter /usr/local/opt/python@3.9/bin/python3.9
   package stig 0.12.5a0, installed using Python 3.11.5
    - stig
   package yewtube 2.9.4, installed using Python 3.11.2
    - yt

One or more packages have a missing python interpreter.
    To fix, execute: pipx reinstall-all
```

**Comment by s-n-g** [comment]
@Bellavene 
Can you follow this: https://github.com/coderholic/pyradio/issues/205#issuecomment-1816777338

**Comment by s-n-g** [comment]
@FedeFofo 

Execute
```
ln -s /Applications/VLC.app/Contents/MacOS/VLC ~/.local/bin
```

and then run `pyradio`

**Comment by FedeFofo** [comment]
That outputs

`ln: /Users/jamesesser/.local/bin: File exists`

and when I ran pyradio I got the same error

**Comment by Bellavene** [comment]
> @FedeFofo
> 
> Execute
> 
> ```
> ln -s /Applications/VLC.app/Contents/MacOS/VLC ~/.local/bin
> ```
> 
> and then run `pyradio`

Better to `sudo ln -s /Applications/VLC.app/Contents/MacOS/VLC  /usr/local/bin/airdrop
`

**Comment by s-n-g** [comment]
> Better to sudo ln -s /Applications/VLC.app/Contents/MacOS/VLC  /usr/local/bin/vlc 

This might work as well...

**Comment by Bellavene** [comment]
> > Better to sudo ln -s /Applications/VLC.app/Contents/MacOS/VLC  /usr/local/bin/vlc
> 
> This might work as well...

It is better, because he doesn't need to add a PATH

**Comment by FedeFofo** [comment]
I ran it, didn't get the same error, but it still didn't work when I opened PyRadio

**Comment by Bellavene** [comment]
but now try run vlc from the prompt

**Comment by FedeFofo** [comment]
Running it from the terminal says

```
2023-11-17 12:45:59.892 vlc[72122:1087164] Sparkle: Error: the bundle being updated at NSBundle </usr/local/bin> (loaded) has no CFBundleIdentifier! This will cause preference read/write to not work properly.
2023-11-17 12:45:59.899 vlc[72122:1087164] -[NSWindowController loadWindow]: failed to load window nib file 'MainWindow'.
2023-11-17 12:45:59.899 vlc[72122:1087164] -[NSWindowController loadWindow]: failed to load window nib file 'MainWindow'.
2023-11-17 12:45:59.899 vlc[72122:1087164] -[NSWindowController loadWindow]: failed to load window nib file 'MainWindow'.

```

it still works to run it normally though

**Comment by s-n-g** [comment]
Do you still get the window up?
Can you play a stream with it?

For example
```
vlc http://somafm.com/illstreet.pls
```

**Comment by Bellavene** [comment]
Strange, should be

 ```
VLC media player 3.0.18 Vetinari (revision 3.0.18-0-ge9eceaed4d)
[000000012b804170] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[000000012a608cf0] main playlist: playlist is empty
```

Ok, maybe the actual vlc executable differs.
Now type `sudo rm -rf /usr/local/bin/vlc`

And we must edit the python script to execute `open -a VLC.app`

**Comment by Bellavene** [comment]
> vlc http://somafm.com/illstreet.pls

of course

**Comment by Bellavene** [comment]
open -a VLC.app PATH/TO/file
works great though

**Comment by s-n-g** [comment]
@FedeFofo 

Close all terminals (right click on the Terminal icon and select **Quit**)

Then open a new terminal and 

```
/Applications/VLC.app/Contents/MacOS/VLC http://somafm.com/illstreet.pls
```
And then
```
vlc http://somafm.com/illstreet.pls
```

Do both of these work?

**Comment by s-n-g** [comment]
@Bellavene 
Have you tried: https://github.com/coderholic/pyradio/issues/205#issuecomment-1816777338

Does the installation succeeds?

**Comment by Bellavene** [comment]
> @Bellavene Have you tried: [#205 (comment)](https://github.com/coderholic/pyradio/issues/205#issuecomment-1816777338)
> 
> Does the installation succeeds?

I'l try it later, a bit busy right now.

**Comment by s-n-g** [comment]
ok, wait...
Let me see your **PATH** from a previous post

**Comment by Bellavene** [comment]
He doesn't need any path, we just need to change in the python source the execution command from vlc to open -a VLC.app
This will be much simpler for all.

**Comment by s-n-g** [comment]
Execute:

```
sudo ln -s /Applications/VLC.app/Contents/MacOS/VLC  /usr/local/bin/vlc
```

Then try `vlc http://somafm.com/illstreet.pls`

If it does not work, try closing all terminals  (right click on the Terminal icon and select **Quit**)

Open a new terminal and try again `vlc http://somafm.com/illstreet.pls`

**Comment by FedeFofo** [comment]
It works

**Comment by s-n-g** [comment]
> He doesn't need any path, we just need to change in the python source the execution command from vlc to open -a VLC.app
> This will be much simpler for all.

That would work for now, but he would have to edit the same change after every `pyradio` update...

**Comment by s-n-g** [comment]
> It works

ok, now try `pyradio`

It should be able to find VLC now

**Comment by FedeFofo** [comment]
Pyradio still doesn't

**Comment by Bellavene** [comment]
I mean, that we could edit it to 'open -a VLC.app' in pyradio source and no need for `sudo ln`

**Comment by s-n-g** [comment]
> It works but pyradio still doesn't

What does it say?
Cannot find a player?

**Comment by FedeFofo** [comment]
Yes same error as before

**Comment by s-n-g** [comment]
> Yes same error as before

I do not understand...

**Comment by s-n-g** [comment]
> I mean, that we could edit it to 'open -a VLC.app' in pyradio source and no need for sudo ln then

You mean permanently?
Maybe... I would have to look into it...

**Comment by Bellavene** [comment]
> > Yes same error as before
> 
> I do not understand...

Something in pyradio script is broken. I'l check it later, though I am not best at it

**Comment by Bellavene** [comment]
Could try?
```
alias vlc=/Applications/VLC.app/Contents/MacOS/VLC
vlc http://somafm.com/illstreet.pls
```

**Comment by s-n-g** [comment]
I think I got it

```
sudo ln -s /Applications/VLC.app/Contents/MacOS/VLC  /usr/local/bin/cvlc
```

I believe this would work (tested it on **Monteray**)

This is a `pyradio` problem, I will fix it for the next release...

**Comment by FedeFofo** [comment]
That works, but when I open pyradio it doesn't work

**Comment by Bellavene** [comment]
Still I believe it is better to `open -a VLC.app`, if there is no other control than open the playlist.

**Comment by s-n-g** [comment]
> Still I believe on macos it is better to open -a VLC.app, if there is no need for other control than to open the playlist.

I really cannot tell
I will look into it...

**Comment by s-n-g** [comment]
The problem is that `open -a VLC.app` will open a window, which is not what we want for `pyradio`

Can we make `open -a VLC.app` not open a window?

**Comment by Bellavene** [comment]
We can, if we install vlc the right way
`brew install vlc`

**Comment by Bellavene** [comment]
Or as a workaround, launch it in the background
`open -g -a VLC.app`

**Comment by s-n-g** [comment]
The window still opens up...

**Comment by s-n-g** [comment]
@FedeFofo 

I have been testing it for a while and it seems the VLC implementation on MacOS is currently broken...
I'm sorry...

**Comment by Bellavene** [comment]
> The window still opens up...
Oops, sorry
`open -j -a VLC.app`

**Comment by s-n-g** [comment]
> Oops, sorry, -g was to open in background
> this works
> open -ja VLC.app

This one looks promising!

**Comment by Bellavene** [comment]
> > Oops, sorry, -g was to open in background
> > this works
> > open -ja VLC.app
> 
> This one looks promising!

In fact you always can do `open -h` or `man open` to check available commands

**Comment by Bellavene** [comment]
> @FedeFofo
> 
> I have been testing it for a while and it seems the VLC implementation on MacOS is currently broken... I'm sorry...
> 
> It seems MacOS VLC does not support all the command line parameters supported by linux and windows VLC, so it finds an "unknown parameter and it terminates with an error....

It supports it like in Linux, if you install it like in Linux, through a package manager or manually right.

**Comment by s-n-g** [comment]
> It supports it like in Linux, if you install it like in Linux, through a package manager or manually right.

I have just installed it manually from its site (dmg file) and I see that `--no-one-instance` is not there

**Comment by Bellavene** [comment]
> > It supports it like in Linux, if you install it like in Linux, through a package manager or manually right.
> 
> I have just installed it manually from its site (dmg file) and I see that `--no-one-instance` is not there

Because dmg file contains only the actual app without shell support.
Really the best option is a package manager like in linux. Homebrew is the best one for macos.

**Comment by s-n-g** [comment]
Either way, we will have to support all installation options, people may not want to use homebrew.

**Comment by Bellavene** [comment]
Yes, that's why I offered `open -ja` method

**Comment by s-n-g** [comment]
BTW, when installed through homebrew, do we still have the same executable?

`/Applications/VLC.app/Contents/MacOS/VLC`

**Comment by Bellavene** [comment]
Yes, it installs VLC.app as well

**Comment by s-n-g** [comment]
So, if `/Applications/VLC.app/Contents/MacOS/VLC` is always there, I could just use that as the command...

Each player has a **PLAYER_CMD** variable; I could set it to that, when on MacOS

**Comment by Bellavene** [comment]
But again, then better is with `open` command.

**Comment by s-n-g** [comment]
> But again, then better is with open command.

The other way is easier for me :rofl: 
Less testing needed :wink:

**Comment by Bellavene** [comment]
> > But again, then better is with open command.
> 
> The other way is easier for me 🤣 Less testing needed 😉

What if is installed in another place? Like `~/Applications/VLC.app/Contents/MacOS/VLC`

**Comment by s-n-g** [comment]
> What if it is installed in another place? Like ~/Applications/VLC.app/Contents/MacOS/VLC
Yes, that would be a problem...

On the other hand, on testing `open -ja VLC.app ...` , I realized that the VLC icon appears in the system tray... That's a no no

And I do not see an option to prevent it (in `open -h`)

**Comment by Bellavene** [comment]
Thats why brew is the best option in the first place 😄

**Comment by Bellavene** [comment]
I really don't see a reason to install most applications manually

**Comment by s-n-g** [comment]
But then again, if we can have it either as 
```
/Applications/VLC.app/Contents/MacOS/VLC
```
or

```
~/Applications/VLC.app/Contents/MacOS/VLC
```
that's not a problem for me, I can search for existence of either!

**Comment by Bellavene** [comment]
True, if it works the same as clvc, as you metioned.

**Comment by s-n-g** [comment]
> I really don't see a reason to install most applications manually

You are an advanced user, so you know the system, and know what you are doing...

Things are different for someone like me (a newbie on MacOS), though :wink:

**Comment by Bellavene** [comment]
> > I really don't see a reason to install most applications manually
> 
> You are an advanced user, so you know the system, and know what you are doing...
> 
> Things are different for someone like me (a newbie on MacOS), though 😉
but then `alias="/Applications/VLC.app/Contents/MacOS/VLC"; vlc` will also do the trick

**Comment by s-n-g** [comment]
https://github.com/coderholic/pyradio/assets/5807638/b6b035ae-dfc7-4889-9b92-f2387f713e8a

**Comment by s-n-g** [comment]
> True, if it works the same as cvlc, as you mentioned.
> but then it is strange that 'sudo ln' didn't work.

Yes, that one was strange, but we'll test it again with the "fixed" impl.
I will update asap

And will update the script to test the installation...

**Comment by s-n-g** [comment]
@Bellavene 

Here's the update script to test `pipx` installation, save it as issue205 in your home folder, and execute it

```
cd
chmod +x issue205
./issue205
```

**issue205**

```
#!/bin/bash
python3 -m pipx reinstall-all
cd
rm -rf tmp_pyradio 2>/dev/null
rm install.py build_install_pyradio 2>/dev/null
mkdir tmp_pyradio
cd tmp_pyradio
curl -L  https://github.com/coderholic/pyradio/archive/refs/tags/0.9.2.19.tar.gz -o 0.9.2.19.tar.gz
tar xzf 0.9.2.19.tar.gz
curl -L https://github.com/s-n-g/pyradio/raw/devel/devel/build_install_pyradio -o build_install_pyradio
mv build_install_pyradio pyradio-0.9.2.19/devel
chmod +x pyradio-0.9.2.19/devel/build_install_pyradio
curl -L https://github.com/s-n-g/pyradio/raw/devel/pyradio/install.py -o install.py
mv install.py pyradio-0.9.2.19/pyradio
cd pyradio-0.9.2.19
./devel/build_install_pyradio
python3 -m pipx ensurepath
```

For VLC:
```
sudo ln -s /Applications/VLC.app/Contents/MacOS/VLC /usr/local/bin/cvlc
```

**Comment by s-n-g** [comment]
@FedeFofo 

Execute
```
cd
rm -rf tmp_pyradio
cd tmp_pyradio
curl -L https://github.com/s-n-g/pyradio/archive/refs/heads/devel.zip -o devel.zip
unzip  devel.zip
cd pyradio-devel
python3 -m pip install .
```

Finally...
```
sudo rm /usr/local/bin/vlc /usr/local/bin/cvlc
rm ~/.local/bin/vlc ~/.local/bin/cvlc
sudo ln -s /Applications/VLC.app/Contents/MacOS/VLC /usr/local/bin/cvlc
pyradio
```

**Comment by s-n-g** [comment]
Good night to you both and thank you for your help and availability to debug this!

**Comment by s-n-g** [comment]
I believe that version **0.9.2.21** has addressed all issues (I finally managed to install Sonoma and tested it there too)...

Do you agree?
Can I close this issue?
