### ISSUE TITLE
macos - 'Namespace' object has no attribute 'python2'

### ISSUE THREAD

**Issue by tjex** [coderholic/pyradio#208]
Trying to re-install pyradio after it stopped working for some reason.

Ran through the installation instructions, as seen below and am getting messages related to python2, despite running everything with python3.

```text
sys > python3 -m pip install requests rich pipx
python3 -m pipx ensurepath

Requirement already satisfied: requests in ./.local/share/venv/sys/lib/python3.11/site-packages (2.31.0)
Requirement already satisfied: rich in ./.local/share/venv/sys/lib/python3.11/site-packages (13.5.2)
Requirement already satisfied: pipx in ./.local/share/venv/sys/lib/python3.11/site-packages (1.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.local/share/venv/sys/lib/python3.11/site-packages (from requests) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in ./.local/share/venv/sys/lib/python3.11/site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.local/share/venv/sys/lib/python3.11/site-packages (from requests) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/share/venv/sys/lib/python3.11/site-packages (from requests) (2023.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./.local/share/venv/sys/lib/python3.11/site-packages (from rich) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.local/share/venv/sys/lib/python3.11/site-packages (from rich) (2.16.1)
Requirement already satisfied: argcomplete>=1.9.4 in ./.local/share/venv/sys/lib/python3.11/site-packages (from pipx) (3.1.1)
Requirement already satisfied: packaging>=20.0 in ./.local/share/venv/sys/lib/python3.11/site-packages (from pipx) (23.1)
Requirement already satisfied: userpath>=1.6.0 in ./.local/share/venv/sys/lib/python3.11/site-packages (from pipx) (1.9.0)
Requirement already satisfied: mdurl~=0.1 in ./.local/share/venv/sys/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich) (0.1.2)
Requirement already satisfied: click in ./.local/share/venv/sys/lib/python3.11/site-packages (from userpath>=1.6.0->pipx) (8.1.7)
/Users/tjex/.local/bin is already in PATH.

⚠️ All pipx binary directories have been added to PATH. If you are sure you want to proceed, try again with the '--force' flag.

Otherwise pipx is ready to go! ✨ 🌟 ✨

~
sys > cd
python3 install.py

                     _____       _____           _ _
                    |  __ \     |  __ \         | (_)
                    | |__) |   _| |__) |__ _  __| |_  ___
                    |  ___/ | | |  _  // _` |/ _` | |/ _ \
                    | |   | |_| | | \ \ (_| | (_| | | (_) |
                    |_|    \__, |_|  \_\__,_|\__,_|_|\___/
                            __/ |
                           |___/

                               installation script
                                   running on

Traceback (most recent call last):
  File "/Users/tjex/install.py", line 1476, in <module>
    if PY3 and not args.python2:
                   ^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'python2'
```

which python3:
```text
/Users/tjex/.local/share/venv/sys/bin/python3
```

which python:
```text
/Users/tjex/.local/share/venv/sys/bin/python
```

python is symlinked to python3. I assume this is correct and default behaviour as I didn't do this myself...
```text
lrwxr-xr-x tjex staff  10B Wed 16 Aug python ⇒ python3.11
lrwxr-xr-x tjex staff  10B Wed 16 Aug python3 ⇒ python3.11
lrwxr-xr-x tjex staff  44B Wed 16 Aug python3.11 ⇒ /opt/homebrew/opt/python@3.11/bin/python3.11
```

**Comment by s-n-g** [comment]
Hi @tjex 

Probably my bad...
Let me have a look...

**Comment by s-n-g** [comment]
Yes, my bad...

I will fix this for the next release

in the meantime, you can

```
sed -i bck '1386a \
    parser.add_argument("--python2", action="store_true", help=SUPPRESS) \
\
' install.py && python3 install.py
```

Hope it works

**Comment by tjex** [comment]
not a prob. Thanks for the speedy reply 😃

It got me past the initial block, but then gave me an error that pipx was not found.

I'm happy to wait till the next release if it's preferrable. But also happy to bug fix it here if it's useful for you for that next release. However you like 👍

```text
Installing PyRadio...
Using directory: "/Users/tjex/.config/pyradio/data/.cache"
Old "/Users/tjex/.config/pyradio/data/.cache" found. Deleting...
Downloading PyRadio source code...
  url: "https://github.com/coderholic/pyradio/archive/0.9.2.20.zip"
  filename: "/Users/tjex/.config/pyradio/data/.cache/pyradio-0.9.2.20.zip"
Extracting RyRadio source code...


Error: pipx not found.
       Please install pipx and try again


An error occured during the installation!
This should have never had happened...
Please report this at http://github.com/coderholic/pyradio/issues
```

`which pipx`:
```
/Users/tjex/.local/share/venv/sys/bin/pipx
```

**Comment by s-n-g** [comment]
Yes, I would rather have you bug fix it here, thank you for being available

BTW, are you on Sonoma by any chance? I have had various bug reports for Sonoma installations, but I haven't been able to install it (yet?); still working on Monterey...

Anyway, I have prepared a test release at my personal repo, so can you please

```
cd
rm install.py
curl https://raw.githubusercontent.com/s-n-g/pyradio/master/pyradio/install.py -o install.py
python3 install.py --sng-master
```

and post the result?

**Comment by tjex** [comment]
Glad to be of assistance :)
I'm on Ventura 13.5.

Still fails. Complaining about pyradio venv as seen below. 


```text
                     _____       _____           _ _
                    |  __ \     |  __ \         | (_)
                    | |__) |   _| |__) |__ _  __| |_  ___
                    |  ___/ | | |  _  // _` |/ _` | |/ _ \
                    | |   | |_| | | \ \ (_| | (_| | | (_) |
                    |_|    \__, |_|  \_\__,_|\__,_|_|\___/
                            __/ |
                           |___/

                               installation script
                                   running on

                   _____       _   _                    ____
                  |  __ \     | | | |                  |___ \
                  | |__) |   _| |_| |__   ___  _ __      __) |
                  |  ___/ | | | __| '_ \ / _ \| '_ \    |__ <
                  | |   | |_| | |_| | | | (_) | | | |   ___) |
                  |_|    \__, |\__|_| |_|\___/|_| |_|  |____/
                          __/ |
                         |___/



Installing PyRadio...
Using directory: "/Users/tjex/.config/pyradio/data/.cache"
Old "/Users/tjex/.config/pyradio/data/.cache" found. Deleting...
Downloading PyRadio source code...
  url: "https://github.com/s-n-g/pyradio/archive/master.zip"
  filename: "/Users/tjex/.config/pyradio/data/.cache/pyradio-master.zip"
Extracting RyRadio source code...
Looking for pipx ... 1.2.0
Installing to existing venv 'pyradio'

⚠️ Not removing existing venv /Users/tjex/.local/pipx/venvs/pyradio because it was not created in this session
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/tjex/.local/share/venv/sys/lib/python3.11/site-packages/pipx/__main__.py", line 14, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/tjex/.local/share/venv/sys/lib/python3.11/site-packages/pipx/main.py", line 863, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tjex/.local/share/venv/sys/lib/python3.11/site-packages/pipx/main.py", line 214, in run_pipx_command
    return commands.install(
           ^^^^^^^^^^^^^^^^^
  File "/Users/tjex/.local/share/venv/sys/lib/python3.11/site-packages/pipx/commands/install.py", line 59, in install
    venv.create_venv(venv_args, pip_args)
  File "/Users/tjex/.local/share/venv/sys/lib/python3.11/site-packages/pipx/venv.py", line 166, in create_venv
    pipx_pth = get_site_packages(self.python_path) / PIPX_SHARED_PTH
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tjex/.local/share/venv/sys/lib/python3.11/site-packages/pipx/util.py", line 131, in get_site_packages
    output = run_subprocess(
             ^^^^^^^^^^^^^^^
  File "/Users/tjex/.local/share/venv/sys/lib/python3.11/site-packages/pipx/util.py", line 176, in run_subprocess
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tjex/.local/pipx/venvs/pyradio/bin/python'
The installation has failed!!!
Please report this at https://github.com/coderholic/pyradio/issues



An error occured during the installation!
This should have never had happened...
Please report this at http://github.com/coderholic/pyradio/issues
```

pyenv dir:
```text
~/.local/pipx/venvs/pyradio
sys > ls -l
drwxr-xr-x tjex staff 416B Sat 26 Aug bin
drwxr-xr-x tjex staff  96B Sat 26 Aug include
drwxr-xr-x tjex staff  96B Sat 26 Aug lib
.rw-r--r-- tjex staff 4.0K Sat 26 Aug pipx_metadata.json
.rw-r--r-- tjex staff 377B Sat 02 Dec pyvenv.cfg

~/.local/pipx/venvs/pyradio
sys > cat pyvenv.cfg
home = /opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/bin
include-system-site-packages = false
version = 3.11.6
executable = /opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/bin/python3.11
command = /Users/tjex/.local/share/venv/sys/bin/python3 -m venv --without-pip /Users/tjex/.local/pipx/venvs/pyradio
```

**Comment by s-n-g** [comment]
I think this is a `pipx` thing...

It is looking for python (the `command = ` part):
```
/Users/tjex/.local/pipx/venvs/pyradio/bin/python
```

but it's not there...

The `executable = ` part, does it exist?

```
/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/bin/python3.11
```

**Comment by s-n-g** [comment]
If the executable =  part
```
/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/bin/python3.11
```
does exist, can you replace

```
command = /Users/tjex/.local/share/venv/sys/bin/python3 -m venv --without-pip /Users/tjex/.local/pipx/venvs/pyradio
```
with
```
command = /opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/bin/python3.11 -m venv --without-pip /Users/tjex/.local/pipx/venvs/pyradio
```

and try again?

**Comment by s-n-g** [comment]
If this one fails as well, let's go the "brute force" way

```
cd
rm -rf /Users/tjex/.local/pipx/venvs/pyradio
python3 install.py --sng-master
```

**Comment by s-n-g** [comment]
What I imagine has happened is that at some point you upgraded `python` and `pipx` was left trying to find the previous version, or something...

Anyway, I am happy it worked!
Closing...
