### ISSUE TITLE
New Install - Error Occured

### ISSUE THREAD

**Issue by Antavatech** [coderholic/pyradio#223]
**System (please complete the following information):**
 - OS: "Raspbian GNU/Linux 11 (bullseye)
 - **Python** version: Python 3.9.2
 - `pipx` version (if applicable): 0.12.3.1
 - `pipx` installation method: Fully isolated
 - **PyRadio** Version: 0.9.2.22

**Terminal output**
```
Installing PyRadio...
Using directory: "/home/pi/.config/pyradio/data/.cache"
Old "/home/pi/.config/pyradio/data/.cache" found. Deleting...
Downloading PyRadio source code...
  url: "https://github.com/coderholic/pyradio/archive/0.9.2.22.zip"
  filename: "/home/pi/.config/pyradio/data/.cache/pyradio-0.9.2.22.zip"
  ** file found in cache!
Extracting RyRadio source code...
Looking for pipx ... 0.12.3.1
Installing to existing directory '/home/pi/.local/pipx/venvs'
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pipx/__main__.py", line 5, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 496, in cli
    exit(run_pipx_command(parsed_pipx_args, binary_args))
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 147, in run_pipx_command
    commands.install(
  File "/usr/lib/python3/dist-packages/pipx/commands.py", line 312, in install
    if venv.get_venv_metadata_for_package(package).package_version is None:
  File "/usr/lib/python3/dist-packages/pipx/Venv.py", line 65, in get_venv_metadata_for_package
    data = json.loads(
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
The installation has failed!!!
Please report this at https://github.com/coderholic/pyradio/issues

An error occured during the installation!
This should have never had happened...
Please report this at http://github.com/coderholic/pyradio/issues
```

**Additional comments**
Anything else to add?

**Comment by s-n-g** [comment]
Hi @Antavatech 

This is a `pipx` error.

A bit of searching ([1], [2]) tells me that your `pipx` is too old and does not support python 3.9; you need to have `pipx 0.16.3` for this to work

Can you update `pipx`?

__
[1] https://github.com/pypa/pipx/issues/702
[2] https://bugs.launchpad.net/ubuntu/+source/python-pipx/+bug/1926806

**Comment by s-n-g** [comment]
For package `pipx` I get

https://packages.debian.org/search?searchon=names&keywords=pipx

Since **Raspbian** is based on **Debian**, I guess you could update it (maybe from `backports`)?

If that does not work, try **uninstalling** `pipx` (the package provided by the OS), and

```
rm -rf ~/.local/pipx
python3 -m pip install --user pipx
```

If that works, check the installed package's version
```
python3 -m pipx --version
```

If it's older than `0.6.3`, remove it

```
python3 -m pip uninstall pipx
```

Since you got to this point, you have to go with the old instillation mode, [Debian and derivatives](https://github.com/coderholic/pyradio/blob/master/docs/linux.md#debian-and-derivatives). The commands there are for pure debian; you may have to adjust for Raspbian

Hope something (anything of the above) works!

**Comment by s-n-g** [comment]
I believe I can close this one...
