### ISSUE TITLE
NameError: name 'netifaces' is not defined

### ISSUE THREAD

**Issue by samuk** [coderholic/pyradio#225]
**System (please complete the following information):**
 - OS: Bookworm
 - **Python** version: Python 3.11.2
 - `pipx` version (if applicable): 1.1.0
 - `pipx` installation method: System dependent 
 - **PyRadio** Version:  0.9.2.24

**Terminal output**
```

bristolfish@Mycodo:~ $ pyradio
Traceback (most recent call last):
  File "/home/bristolfish/.local/bin/pyradio", line 8, in <module>
    sys.exit(shell())
             ^^^^^^^
  File "/home/bristolfish/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/main.py", line 650, in shell
    read_config(pyradio_config)
  File "/home/bristolfish/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/main.py", line 986, in read_config
    ret = pyradio_config.read_config()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bristolfish/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/config.py", line 2110, in read_config
    nip = IPsWithNumbers(
          ^^^^^^^^^^^^^^^
  File "/home/bristolfish/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/server.py", line 103, in __init__
    if fat or len(ips.IPs) > 2:
                  ^^^^^^^
  File "/home/bristolfish/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/server.py", line 44, in IPs
    self._get_all_ips()
  File "/home/bristolfish/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/server.py", line 50, in _get_all_ips
    self._IPs = self._get_linux_ips()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bristolfish/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/server.py", line 70, in _get_linux_ips
    interfaces = netifaces.interfaces()
                 ^^^^^^^^^
NameError: name 'netifaces' is not defined

```
**Additional comments**
Anything else to add?

**Comment by s-n-g** [comment]
Hi @samuk 

Module `netifaces` is missing (not installed?)

Can you try this and post the output?

```
sudo apt-get install python3-netifaces
```

Is the module installed?

Can you execute `pyradio`?

**Comment by samuk** [comment]
Ah nice that fixed it, thanks maybe it should be listed as a dependency if not pulled in automatically.

ycodo:~/pyradio $ sudo apt-get install python3-netifaces
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  python3-netifaces

Off topic: Have you considered adding FIP? It's pretty good: https://community.roonlabs.com/t/new-fip-streaming-url/87335/6

**Comment by s-n-g** [comment]
> Ah nice that fixed it, thanks maybe it should be listed as a dependency if not pulled in automatically.

You are right I have omitted it from the list of dependencies...

> Off topic: Have you considered adding FIP? It's pretty good: https://community.roonlabs.com/t/new-fip-streaming-url/87335/6

I will have a look, thanks!
