### ISSUE TITLE
[BUG]  Issues when I press i on 60 North

### ISSUE THREAD

**Issue by nrichw-eta** [coderholic/pyradio#236]
**Describe the bug**
When I add 60 north 320k (https://60north.radio, http://r3.zetcast.net/stream) to my playlist and press i to get info afterwards, it makes the interface unusable by first closing the TUI and giving a trace back then re-entering the TUI but leaving no binding working except ^C to exit. The audio still plays until ^C is pressed. This does NOT happen with the FLAC stream. If I duplicate the entry for the FLAC station then edit the entry to use the 320k stream the bug will happen.

**To Reproduce**
1. Press a and add Station Name and Stream URL as normal
2. Select station and press i
3. Traceback will appear, then TUI in unusable state

**Expected behavior**
I expected the Station info box to appear as normal as should happen 

**System (please complete the following information):**
 - OS: Linux Mint Debian Edition 6 "Faye"
 - **Python** version: 3.11.2
 - `pipx` version (if applicable): 1.1.0
 - `pipx` installation method: via pip. pip installed with apt
 - **PyRadio** Version: 0.9.3.2

**Additional context**

```Reading playlist...
Traceback (most recent call last):
  File "/home/nicoler/.local/bin/pyradio", line 8, in <module>
    sys.exit(shell())
             ^^^^^^^
  File "/home/nicoler/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/main.py", line 898, in shell
    curses.wrapper(pyradio.setup)
  File "/usr/lib/python3.11/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicoler/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/radio.py", line 1064, in setup
    self.run()
  File "/home/nicoler/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/radio.py", line 1943, in run
    ret = self.keypress(c)
          ^^^^^^^^^^^^^^^^
  File "/home/nicoler/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/radio.py", line 8505, in keypress
    self._normal_station_info()
  File "/home/nicoler/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/radio.py", line 5064, in _normal_station_info
    self._show_station_info()
  File "/home/nicoler/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/radio.py", line 4335, in _show_station_info
    txt, tail = self.player.get_info_string(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicoler/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/player.py", line 681, in get_info_string
    a_list[n] = '|' + a_list[n]
                             ^
NameError: name 'n' is not defined```

**Comment by s-n-g** [comment]
Hi @nrichw-eta 

I cannot reproduce, but I believe I have found what's going on...

Can you execute this command in a terminal?

```
cd
echo "--- /home/nicoler/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/player.py
+++ /home/nicoler/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/player.py
@@ -678,7 +678,7 @@ class Player(object):
         # logger.debug('\n\n\n')

         if 'Codec:' not in a_list[-1]:
-            a_list[n] = '|' + a_list[n]
+            a_list.append('        Codec:')

         # if a_list[1].startswith('_'):
         #     a_list[1] = '|' + a_list[1]" > issue236.patch
patch -b /home/nicoler/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/player.py < issue236.patch
```

This will
1. patch /home/nicoler/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/player.py
2. create /home/nicoler/.local/pipx/venvs/pyradio/lib/python3.11/site-packages/pyradio/player.py.orig 

Afterwards, check if the bug is fixed and report back here

**Comment by nrichw-eta** [comment]
this seems to have solved it! Thank you!

**Comment by s-n-g** [comment]
ok, pushing it into `devel`
Thank you for reporting!
