### ISSUE TITLE
[BUG] pyradio deletes ~/pyradio-recordings.

### ISSUE THREAD

**Issue by amano-kenji** [coderholic/pyradio#255]
**Describe the bug**

I execute pyradio in firejail which is an application sandbox.

My pyradio firejail profile creates ~/pyradio-recordings and puts it in a whitelist so that ~/pyradio-recordings is available to pyradio.

However, pyradio tries to delete ~/pyradio-recordings while firejail is holding onto it. Thus, I see this error

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.12/pyradio", line 8, in <module>
    sys.exit(shell())
             ^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyradio/main.py", line 394, in shell
    read_config(pyradio_config)
  File "/usr/lib/python3.12/site-packages/pyradio/main.py", line 988, in read_config
    ret = pyradio_config.read_config()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyradio/config.py", line 2126, in read_config
    self._read_config(distro_config=True)
  File "/usr/lib/python3.12/site-packages/pyradio/config.py", line 2393, in _read_config
    self._make_sure_dirs_exist()
  File "/usr/lib/python3.12/site-packages/pyradio/config.py", line 2471, in _make_sure_dirs_exist
    remove_tree(self.opts['recording_dir'][1])
  File "/usr/lib/python3.12/shutil.py", line 796, in rmtree
    onexc(os.rmdir, path, err)
  File "/usr/lib/python3.12/shutil.py", line 794, in rmtree
    os.rmdir(path, dir_fd=dir_fd)
OSError: [Errno 16] Device or resource busy: '/home/guardian/pyradio-recordings'
```

**System (please complete the following information):**
 - OS: gentoo linux
 - **Python** version: 3.12
 - **PyRadio** Version: 0.9.3.11
 - Player used: mpv

**Comment by s-n-g** [comment]
Ok, easy to fix...


In the meantime, a quick fix:

Create any file in ~/pyradio-recordings
pyradio will try to delete the folder only if it's empty

**Comment by s-n-g** [comment]
fixed in `devel`
uploaded to [master](https://github.com/coderholic/pyradio/tree/master/)

**Comment by amano-kenji** [comment]
I don't know whether that's a right solution.  If pyradio fails to delete ~/pyradio-recordings, that's fine. If pyradio succeeds in deleting it, a newly created directory at ~/pyradio-recordings will either be deleted or shunted somewhere else after pyradio firejail sandbox is destroyed.

**Comment by s-n-g** [comment]
> If pyradio fails to delete ~/pyradio-recordings, that's fine.
This is your case, so...

> If pyradio succeeds in deleting it...
Since you have it "locked" (I don't know how firejail works), but that's how I understand it...
It won't be deleted, it will be available for the next time you run pyradio

I am probably missing something here, since I don't know how firejail works, but in any case, just creating a file in ~/pyradio-recordings will stop pyradio from trying to delete it

**Comment by amano-kenji** [comment]
Okay. I will open a new issue if the new behavior becomes a problem.
