### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by martynjy** [coderholic/pyradio#33]
Traceback (most recent call last):
  File "/usr/bin/pyradio", line 9, in <module>
    load_entry_point('pyradio==0.5.2', 'console_scripts', 'pyradio')()
  File "/usr/lib/python3.5/site-packages/pyradio/main.py", line 45, in shell
    name, url = [s.strip() for s in row]
ValueError: too many values to unpack (expected 2)

**Comment by coderholic** [comment]
What's in your stations.csv file?

**Comment by martynjy** [comment]
Yes. Bad csv entry. Sorted.
