### ISSUE TITLE
crash... TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by s-n-g** [coderholic/pyradio#51]
This is what i get when i try to start playback:

Traceback (most recent call last):
  File "/usr/bin/pyradio", line 11, in <module>
    load_entry_point('pyradio==0.5.2', 'console_scripts', 'pyradio')()
  File "/usr/lib/python3.6/site-packages/pyradio/main.py", line 101, in shell
    curses.wrapper(pyradio.setup)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python3.6/site-packages/pyradio/radio.py", line 66, in setup
    self.run()
  File "/usr/lib/python3.6/site-packages/pyradio/radio.py", line 152, in run
    ret = self.keypress(c)
  File "/usr/lib/python3.6/site-packages/pyradio/radio.py", line 218, in keypress
    self.playSelection()
  File "/usr/lib/python3.6/site-packages/pyradio/radio.py", line 182, in playSelection
    self.player.play(stream_url)
  File "/usr/lib/python3.6/site-packages/pyradio/player.py", line 47, in play
    opts = self._buildStartOpts(streamUrl, isPlayList)
  File "/usr/lib/python3.6/site-packages/pyradio/player.py", line 110, in _buildStartOpts
    if "not found" not in out[0]:
TypeError: a bytes-like object is required, not 'str'

I fixed this one by changing
  if "not found" not in out[0]:
to
  if "not found" not in str(out[0]):

python 3.6.5

**Comment by coderholic** [comment]
Thanks for reporting. Can you submit a PR?

**Comment by s-n-g** [comment]
What's a PR? lol

Probably a patch request?
I'm sorry i'm not familiar with github...

**Comment by coderholic** [comment]
A pull request. https://help.github.com/articles/about-pull-requests/

**Comment by s-n-g** [comment]
ok, let me look into it...

**Comment by s-n-g** [comment]
Did i get it right?

**Comment by coderholic** [comment]
👍
