### ISSUE TITLE
pyradio doesn't run after update of phyton

### ISSUE THREAD

**Issue by Catoptrix** [coderholic/pyradio#61]
here is the output:

Traceback (most recent call last):
  File "/usr/bin/pyradio", line 11, in <module>
    load_entry_point('pyradio==0.5.2', 'console_scripts', 'pyradio')()
  File "/usr/lib/python3.7/site-packages/pyradio/main.py", line 89, in shell
    name, url = [s.strip() for s in row]
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by Catoptrix** [comment]
I reinstalled it after cleaning the cache and After i manually delted the .config/pyradio folder. since then I had no problems. Seems my csv had some error in it. Solved
