### ISSUE TITLE
Updating pyradio on PyPi (pip)

### ISSUE THREAD

**Issue by s-n-g** [coderholic/pyradio#78]
@coderholic 

Can you please take a look at #77 regarding updating pyradio in PyPi?

**Comment by jirikrepl** [comment]
it would be nice to update it, can anyone do it?

**Comment by FestplattenSchnitzel** [comment]
FYI you can install `pyradio` via `pip`s [VCS Support](https://pip.pypa.io/en/stable/topics/vcs-support/) directly from this Git Repository:

**Install**
```shell
pip install git+https://github.com/coderholic/pyradio.git
# This might not be necessary, if [python3-]psutil is already installed.
pip install psutil
```

**Upgrade**
```shell
pip install --upgrade git+https://github.com/coderholic/pyradio.git psutil
```

**Uninstall**
```shell
pip uninstall pyradio psutil
```

(If you use [pipx](https://pypa.github.io/pipx/), make sure to inject `psutil` with `pipx inject pyradio psutil`.)

**Comment by s-n-g** [comment]
Hi @FestplattenSchnitzel 

Although using `pip`'s [VCS Support](https://pip.pypa.io/en/stable/topics/vcs-support/) is correct, it is currently not 100% suitable for a `pyradio` installation.

Since I never had [PyPI](https://pypi.org/) access for this project (I am not the original programmer, you see), I have created a workaround; the [install.py](https://raw.githubusercontent.com/coderholic/pyradio/master/pyradio/install.py) script.

This script will:
1. build and install the wheel (using `pip`). \
It will download the **stable** (i.e. **tagged**) version from the repo and work with it.
2. install html documentation and man pages \
Using the `pip` method will not update the documentation, and having outdated documentation is not the best thing to face especially when you run into problems or want to customize things.
3. install a Desktop File (Start Menu link file on Windows). \
This is a nice feature to have on linux, but a must have on Windows.

Furthermore, once `pyradio` is installed, it will automatically check for an update and ask for permission to download and install one (if found). So, the `pip` method is not necessary any more.

Now, one is free to use any method one finds easier, but I would recommend using the `install.py` script for the first installation, and the "automatic" way of updating (using `pyradio -U` is also an option).

**Comment by luzpaz** [comment]
Current pypi version is 0.5.2 (https://pypi.org/project/pyradio/)

**Comment by s-n-g** [comment]
Yes, @luzpaz  I know...

I am not the creator of the project, @coderholic is, and  I do not have access to pypi

Either way, maybe it's for the best; providing a custom installation method allows for the installation of man pages, html help etc. which would not be possible through pypi (as far as I know)

**Comment by Scary-Guy** [comment]
So this is a really dumb idea I'm sure but...  what about just renaming the project?

Yeah I know it's not exactly an easy task but it's better than having to try to do workarounds that may be slightly confusing for some people (like me who tried to install via pip first.)

You could call it radiopy or something.

**Comment by s-n-g** [comment]
@Scary-Guy 

That would be a solution, I know, but one I'm not ready to even consider right now.

I undestand that using a script like `install.py` is not an orthodox way, but on the other hand, it is only required once, then the program will essentially update itself.

The downside of renaming the repo altogether, effectively creating a new project, would lead to losing all the hisyory, issues, etc. we have in this repo, I would not like to do that...

So, for the time being, I think we are good as we are :wink:

**Comment by Scary-Guy** [comment]
Yeah, I mean once it's done it's fine.  However not everyone is so technically minded so I think the simpler things can be made the better.

There's also a good argument of survival of the fittest, and if someone can't figure out how to install something when most of the legwork is done for them (binaries instead of compiling) that maybe they don't necessarily need or deserve to have that program.  But I am kind of a jerk too.

**Comment by j-lakeman** [comment]
Hi guys, any updates on this? Would love to use `pyradio` on Debian-like systems.

After `uv tool install --upgrade git+https://github.com/coderholic/pyradio` I get:

```fish
[I] ~ ❯❯❯ pyradio
Traceback (most recent call last):
  File "/home/xxx/.local/bin/pyradio", line 4, in <module>
    from pyradio.main import shell
  File "/home/xxx/.local/share/uv/tools/pyradio/lib/python3.14/site-packages/pyradio/main.py", line 23, in <module>
    from .radio import PyRadio
  File "/home/xxx/.local/share/uv/tools/pyradio/lib/python3.14/site-packages/pyradio/radio.py", line 28, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Did I miss anything?

Awesome project! Keep up the good work!

**Comment by s-n-g** [comment]
I know almost nothing about `uv`, but I think this will do the job

```
uv tool install --upgrade git+https://github.com/coderholic/pyradio \
--with requests \
--with dnspython \
--with psutil \
--with rich \
--with python-dateutil \
--with netifaces \
--with charset-normalizer 
```

**Comment by j-lakeman** [comment]
Thanks for your help! Unfortunately I ran into this:

<details><summary>Error on Debian Sid</summary>
<p>

```shell
[I] ~ ❯❯❯ uv tool install --upgrade git+https://github.com/coderholic/pyradio \
              --with requests \
              --with dnspython \
              --with psutil \
              --with rich \
              --with python-dateutil \
              --with netifaces \
              --with charset-normalizer
Resolved 16 packages in 2.27s
      Built pyradio @ git+https://github.com/coderholic/pyradio@4917dad4d1251cfb55ca5142809620e18bc5097d
  × Failed to build `netifaces==0.11.0`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit status: 1)

      [stdout]
      running bdist_wheel
      running build
      running build_ext
      checking for getifaddrs...found.
      checking for getnameinfo...found.
      checking for IPv6 socket IOCTLs...not found.
      checking for optional header files...netash/ash.h netatalk/at.h netax25/ax25.h neteconet/ec.h
      netipx/ipx.h netpacket/packet.h netrose/rose.h linux/atm.h linux/llc.h linux/tipc.h.
      checking whether struct sockaddr has a length field...no.
      checking which sockaddr_xxx structs are defined...at ax25 in in6 ipx un rose ash ec ll atmpvc
      atmsvc llc.
      checking for routing socket support...no.
      checking for sysctl(CTL_NET...) support...no.
      checking for netlink support...yes.
      will use netlink to read routing table
      building 'netifaces' extension
      x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -fPIC
      -DNETIFACES_VERSION=0.11.0 -DHAVE_GETIFADDRS=1 -DHAVE_GETNAMEINFO=1 -DHAVE_NETASH_ASH_H=1
      -DHAVE_NETATALK_AT_H=1 -DHAVE_NETAX25_AX25_H=1 -DHAVE_NETECONET_EC_H=1 -DHAVE_NETIPX_IPX_H=1
      -DHAVE_NETPACKET_PACKET_H=1 -DHAVE_NETROSE_ROSE_H=1 -DHAVE_LINUX_ATM_H=1
      -DHAVE_LINUX_LLC_H=1 -DHAVE_LINUX_TIPC_H=1 -DHAVE_SOCKADDR_AT=1 -DHAVE_SOCKADDR_AX25=1
      -DHAVE_SOCKADDR_IN=1 -DHAVE_SOCKADDR_IN6=1 -DHAVE_SOCKADDR_IPX=1 -DHAVE_SOCKADDR_UN=1
      -DHAVE_SOCKADDR_ROSE=1 -DHAVE_SOCKADDR_ASH=1 -DHAVE_SOCKADDR_EC=1 -DHAVE_SOCKADDR_LL=1
      -DHAVE_SOCKADDR_ATMPVC=1 -DHAVE_SOCKADDR_ATMSVC=1 -DHAVE_SOCKADDR_LLC=1 -DHAVE_PF_NETLINK=1
      -I/home/xxx/.cache/uv/builds-v0/.tmpkldFGt/include -I/usr/include/python3.13 -c netifaces.c -o
      build/temp.linux-x86_64-cpython-313/netifaces.o

      [stderr]
      /home/xxx/.cache/uv/builds-v0/.tmpkldFGt/lib/python3.13/site-packages/setuptools/dist.py:765:
      SetuptoolsDeprecationWarning: License classifiers are deprecated.
      !!

              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:

              License :: OSI Approved :: MIT License

              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for
      details.
              ********************************************************************************

      !!
        self._finalize_license_expression()
      netifaces.c:1:10: fatal error: Python.h: No such file or directory
          1 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

hint: This error likely indicates that you need to install a library that provides "Python.h" for `netifaces@0.11.0`
``` 

</p>
</details>

**Comment by s-n-g** [comment]
You probably have to install python3-devel or whatever it's called on sid.

Sorry, I'm at work not on a pc

**Comment by s-n-g** [comment]
on a debian testing box
```
spiros@debiantesting:~/pyradio$ apt search libpython | grep installed
libpython3-dev/testing,now 3.13.9-3+b1 amd64 [installed,automatic]
libpython3-stdlib/testing,now 3.13.9-3+b1 amd64 [installed,automatic]
libpython3.13/testing,now 3.13.12-1 amd64 [installed,automatic]
libpython3.13-dev/testing,now 3.13.12-1 amd64 [installed,automatic]
libpython3.13-minimal/testing,now 3.13.12-1 amd64 [installed,automatic]
libpython3.13-stdlib/testing,now 3.13.12-1 amd64 [installed,automatic]
libpython3.13-testsuite/testing,now 3.13.12-1 all [installed,automatic]
```

So, I would start with `libpython3.13-dev` and go from there

**Comment by j-lakeman** [comment]
Cheers that worked!
FYI to enable OS media controls on Linux installed through `uv` add `--with dbus-next`.
Why does `pyradio` not have all of above requirements as dependencies by default though?

**Comment by s-n-g** [comment]
Actually, there is a requirements.txt file that you can use with uv...
It needs to be a local file though, so:

```
uv tool install --upgrade git+https://github.com/coderholic/pyradio \
  --with-requirements <(curl -sL https://raw.githubusercontent.com/coderholic/pyradio/master/requirements_pipx.txt)   
```

And if you want enable OS media controls, you would:
```
uv tool install --upgrade git+https://github.com/coderholic/pyradio \
  --with-requirements <(curl -sL https://raw.githubusercontent.com/coderholic/pyradio/master/requirements_pipx.txt) \
  --with dbus-next   
```

`curl` must be installed beforehand though
